"""initial

Revision ID: 52256247af94
Revises: 
Create Date: 2024-01-05 11:13:01.739616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52256247af94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
