"""description_of_changes

Revision ID: 789a6759f268
Revises: bcc41104612d
Create Date: 2024-01-05 12:50:42.745723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789a6759f268'
down_revision = 'bcc41104612d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
